# Generated by Django 3.2.25 on 2025-09-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentextra',
            name='roll',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
