# Generated by Django 3.2.25 on 2025-09-01 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_studentextra_roll'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherextra',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
