# Generated by Django 3.0.5 on 2025-08-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_studentextra_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentextra',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
