# Generated by Django 3.0.5 on 2025-08-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_studentextra_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherextra',
            name='qualification',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
