# Generated by Django 3.0.5 on 2025-08-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_auto_20250821_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherextra',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
    ]
