# Generated by Django 3.2.25 on 2025-08-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_teacherextra_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='roll',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='studentextra',
            name='roll',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Roll Number'),
        ),
    ]
